export const NEWS_LIST = 'NEWS_LIST';
export const NEWS_ITEM = 'NEWS_ITEM';

export const SHOW_LOADER_PAGE = 'SHOW_LOADER_PAGE';
export const HIDE_LOADER_PAGE = 'HIDE_LOADER_PAGE';

export const SHOW_LOADER_COMMENTS = 'SHOW_LOADER_COMMENTS';
export const HIDE_LOADER_COMMENTS = 'HIDE_LOADER_COMMENTS';

export const FETCH_ERROR_MESSAGE = 'FETCH_ERROR_MESSAGE';
